version: '3'
services:
  app:
    container_name: prisma_app
    image: node:alpine  # Usando la imagen de Node con Alpine
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules  
    working_dir: /app
    command: npm run start:dev  # Usando tu comando para desarrollo
    restart: always

  db:
    container_name: postgres_db
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
