services:
  app:
    container_name: prisma_app
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    command: npm run start:dev

  db:
    container_name: postgres_db
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
