version: '3.8'
services:
  app:
    container_name: prisma_app
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env  # Este archivo debe contener la variable DATABASE_URL con la URL de la base de datos remota
    volumes:
      - .:/app
    command: npm run start:dev

volumes:
  postgres_data:
